### ISSUE TITLE
Why do I need to flash my Raspi with Raspbian for Robots?

### ISSUE THREAD

**Issue by crearo** [DexterInd/BrickPi3#106]
I have a Raspi 3B+ and a BrickPi3. I've already setup the ordinary Raspi and have been using it for months - has just the right setup I want for it. To use the BrickPi3 I'll have to erase all that and flash a new OS onto it. Why? 
Why can't communicating between the BrickPi3 and Raspi be just a `pip install`? What changes were made in the ordinary Raspbian?

**Comment by CleoQc** [comment]
You do not need to go with Raspbian for Robots. You can do a curl install on your Raspbian if you prefer:
`curl -kL dexterindustries.com/update_brickpi3 | bash`

the scripts are available in this repo and a couple of others. More than one library will get installed and a few helper scripts.

**Comment by crearo** [comment]
Awesome! Thanks a lot. I'll try it out, and reopen if I face an issue.
