### ISSUE TITLE
No Speed Control for set_motor_position

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi3#36]
Hello. The set_motor_position() function does not include the option to control the speed of which the motors turn. You can only control the degrees. The BrickPi+ had this feature but apparently it wasn't added to the BrickPi3.

**Comment by dlech** [comment]
This is an expected function for ev3dev users as well.

**Comment by mattallen37** [comment]
As of PR #40 you can now specify a maximum speed (in percent from 0 to 100) for a motor in Position or DPS mode. This will allow limiting the motor power to e.g. 50%, thus reducing the maximum torque a motor will apply attempting to reach the target (position or speed).

**Comment by dlech** [comment]
I was looking for regulated speed control here (DPS) rather than unregulated (%), e,g, I want to turn the motor 0.5 rotations as 200 deg/sec.

**Comment by mattallen37** [comment]
Eventually I intend to add that functionality as well, which is why the drivers support it (they support sending that value to the firmware). I expect it to take a while to implement into the firmware, so it might be some time before this is fully implemented. For now we can keep this issue open.

**Comment by mattallen37** [comment]
In the meantime, the encoder position and motor PWM control are available, so a user can implement their own algorithm in Python.

**Comment by graykevinb** [comment]
Thanks Matt! Looks awesome. :1st_place_medal:

**Comment by mattallen37** [comment]
The firmware now supports speed control in DPS for motor position targeting. set_motor_limits now supports both motor PWM power limit (applies to set_motor_position and set_motor_dps) and motor DPS speed limit (applies only to set_motor_position).
