### ISSUE TITLE
Error in brickpi3.py library documentation for set_motor_dps

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi3#37]
The documentation for set_motor_dps reads the same as the comments for set_motor_position.
I quote from the documentation.

>      
     |  set_motor_dps(self, port, dps)
     |      Set the motor position in degrees
     |      
     |      Keyword arguments:
     |      port -- The motor port
     |      position -- The target position
     |  
     |  set_motor_position(self, port, position)
     |      Set the motor position in degrees
     |      
     |      Keyword arguments:
     |      port -- The motor port
     |      position -- The target position

> 
As you can see it says they both do the same exact thing.
However functions do two different things. The set_motor_dps function moves the motor by degrees per second. It does not move the motor to a target position.

**Comment by mattallen37** [comment]
Fixed as of PR #40.

**Comment by DexterInd** [comment]
Hey @graykevinb can we close this one out?

**Comment by graykevinb** [comment]
Sure.
