### ISSUE TITLE
Motor status indication

### ISSUE THREAD

**Issue by dlech** [DexterInd/BrickPi3#38]
While working on ev3dev support for BrickPi3, I found a missing feature that is present on other similar devices. There is not any feedback from the motors other than the position.

Other useful feedback would include:
* Running -  the motor is powered
* Stalled - the motor is powered, but not rotating
* Speed - the current speed of the motor
* Overloaded - when running with the speed pid, the motor is not able to reach the target speed
* Holding - when running to a position, indicates that the position has been reached and the position pid is holding the motor at the desired position

See https://github.com/ev3dev/ev3dev/issues/282#issue-59308478 for a table with a comparison of other devices.

**Comment by mattallen37** [comment]
As of PR #40 you can now read the motor status. This includes flags (so far the only flag is the one indicating that the voltage is too low, and the motor is automatically set to float), power (PWM speed setting from -100 to 100, or outside that range which indicates floating), position (encoder position in degrees), and speed (measured speed in degrees per second).

Detecting if a motor is overloaded in DPS mode, or holding in Position mode is very relative to the application. In some cases (an unloaded motor), the motor will stop turning once it's within maybe a couple degrees of the target, but in other cases (a heavy load on a motor), the motor might stop turning when it's still 10 degrees from it's target (at which point the PWM power might be at 20%, but the physical load prohibits it from getting to the exact target). Realistically even an unloaded motor won't reliably get to the exact position specified, but it will keep trying. As the load or target changes, the firmware will continue to attempt to reach the target, but it will never reach it perfectly. Now there is feedback available for the user program to determine when the target is reached (per application).

**Comment by DexterInd** [comment]
@dlech can we close this one out?

**Comment by dlech** [comment]
It will take me a while to figure out if I can actually get enough information from the currently available status items to fill in the blanks.
