### ISSUE TITLE
Allow selection of stop action when running to position

### ISSUE THREAD

**Issue by dlech** [DexterInd/BrickPi3#39]
It would be nice to be able to allow other stop actions when a motor has reached the target position. In ev3dev, we have "hold", which is the current behavior of `set_motor_position` and also "brake" and "coast".

In some applications, it is desirable to not halt so abruptly.

**Comment by mattallen37** [comment]
As mentioned in my comment on issue #38, reaching the target is application specific. As it is, a user can use Python to determine when the target has been reached, and then set the motor to brake or coast.
