### ISSUE TITLE
browserBot example for BrickPi3

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi3#44]
I have ported the [browserBot](https://github.com/DexterInd/BrickPi/tree/master/Software/BrickPi_Python/Project_Examples/browserBot) example to the BrickPi3. I have tested it and it appears to work.

**Comment by graykevinb** [comment]
The code is here:
https://github.com/graykevinb/BrickedPi/tree/master/Software/Python/Projects/browserBot

**Comment by graykevinb** [comment]
I am also a little confused on how to properly have it credited.

**Comment by DexterInd** [comment]
Hey Kevin, did you close the PR?

**Comment by graykevinb** [comment]
Yes, there was an issue I accidently did with the credits that I just fixed.

**Comment by graykevinb** [comment]
Was busy, and forgot. I fixed them and created a new PR
