### ISSUE TITLE
README should include in instructions that setup.py should be run to install the brickpi3 module.

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi3#46]
The installation instructions in the README only tell to run the BrickPi3/Install/install.sh script. This script does not install the brickpi3 module. Shouldn't the install script either install the module or it be included in the installation instructions to run BrickPi3/Software/setup.py?

**Comment by mattallen37** [comment]
Look at [install.sh lines 70-72](https://github.com/DexterInd/BrickPi3/blob/master/Install/install.sh#L70-L72).

**Comment by graykevinb** [comment]
Hmm, interesting. For an odd reason I still had to run it to make it work.

**Comment by mattallen37** [comment]
Were you using Raspbian For Robots or Raspbian? Did you reboot after running install.sh ?

**Comment by graykevinb** [comment]
No I was running raspbian.

**Comment by mattallen37** [comment]
Can you re-produce the problem? If so, can you give me more details (raspbian version, and did you follow the three-step instructions exactly as in the README?) so that I can try to re-produce it? I had tested on Raspbian and Raspbian for Robots, and it worked for me on both.

**Comment by graykevinb** [comment]
Sorry for the late reply. I'll try it again.

**Comment by graykevinb** [comment]
I did a fresh Raspbian install and cloned this repository and ran the install script. I still had to run BrickPi3/Software/Python/install.py in order for me to be able to run `import brickpi3` in python.
This is odd since that script is supposed to be run in the install script.

**Comment by Shoban94** [comment]
Hi @graykevinb , yes that is true, we just noticed that here https://github.com/DexterInd/BrickPi3/blob/master/Install/install.sh#L70 , we are looking for Dexter folder, which isn't present for non Raspbian for Robots users, so you had to run the setup.py from BrickPi3/Software/Python. 

Thanks for bringing it up

**Comment by graykevinb** [comment]
Ahh. Makes perfect sense now. Perhaps it would be a little easier if the folders were simplified to only one folder?

**Comment by mattallen37** [comment]
In initial testing, by cloning to /home/pi/Dexter/BrickPi3 (README step 1 for installing on Raspbian), the Dexter/BrickPi3 directory was created, the repo would be cloned to the correct directory, and the install worked. If it's not working now, I'm not sure what changed.
