### ISSUE TITLE
Regulated Motor Control

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi3#49]
If I am corrected the motors are not regulated, meaning if a force is applied the power will increase to keep it moving the same speed. Currently the motors run unregulated, so they will slow down when a force is applied.

**Comment by mattallen37** [comment]
set_motor_speed is indeed unregulated PWM, with no PID or other algorithm. This allows someone to implement their own motor control algorithm in Python (like the BalanceBot uses). This is not a bug. There are speed and position control algorithms implemented in the firmware if you want regulated motor control (granted the speed control algorithm needs to be improved).

Unless I misunderstood, I think we can close this issue.

**Comment by graykevinb** [comment]
We can. I wasn't reporting a bug, Just requesting a feature. I take then for the future from looking at what features are accepted and rejected that if an algorithm can be pracitcally implemented then the firmware does not need to be updated.

**Comment by mattallen37** [comment]
Regulated speed control _is_ implemented in the firmware (Degrees Per Second control), it just isn't a great implementation (it needs improvement).

If there's a feature that is universal (such as speed or position control of a motor) and doesn't rely on values from an outside source (such as values from a gyro sensor), then I will consider adding it. set_motor_speed specifically sets the PWM power, and is completely unregulated (no algorithm), which is useful for implementing complex algorithms in user code that couldn't reasonably be programmed into the firmware (very application-specific algorithms, such as the complex BalanceBot motor algorithms that use encoder values, gyro values, and values from a remote).

Note that while adding/improving FW motor control algorithms is on my to-do list, I have many other things keeping me busy, so in the meantime you're certainly welcome to implement custom algorithms in Python.
