### ISSUE TITLE
No directions for uninstallation documentatoin for brickpi python module

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi3#50]
This bug also goes for the [BrickPi repository](https://github.com/DexterInd/BrickPi) There are no instructions to remove the brickpi python module. However the setup.py script does support it.(I tried it on the brickpi3) I noticed that they did previously exist on the BrickPi_Python repository. Here's a link of the repo at a point where there is the instructions: [older BrickPi_Python readme](https://github.com/DexterInd/BrickPi_Python/blob/48d1032ddfafb50b7430f673e6a9c0aa836de386/README.md)

**Comment by mattallen37** [comment]
Uninstalling the Python module is not something that we support. If someone needs to uninstall for some reason, [this stackoverflow post](http://stackoverflow.com/questions/1550226/python-setup-py-uninstall) could be helpful.
