### ISSUE TITLE
Custom sensor type does not seem to be working in firmware v1.4.2

### ISSUE THREAD

**Issue by dlech** [DexterInd/BrickPi3#64]
In the ev3dev drivers for BrickPi3, we use the custom sensor type for NXT analog sensors. We have successfully updated our drivers to be compatible with the 1.4.x firmware. Everything else seems to be working except for this. Is it possible you missed a change in the firmware when switching from index to bitwise port numbers? I don't see the firmware source code anywhere to check.

**Comment by mattallen37** [comment]
I tested with Analog_Sensor.py and Analog_Sensors.py, as well as another test program that uses pin 5 to turn on the NXT light sensor LED. Everything seemed to work as expected. Can you give me a specific example that does not work?

**Comment by dlech** [comment]
Thanks for checking. I haven't had a chance to switch back to Raspbian 4 Robots to test it. We should be doing essentially the same thing as Analog_Sensors.py, so it if is working for you, we must be doing something wrong somewhere. I'll keep digging.

**Comment by dlech** [comment]
It turns out that I missed the change in the return value format for custom sensors.
