### ISSUE TITLE
brickpi3.reset_all() sometimes fails to stop motors.

### ISSUE THREAD

**Issue by graykevinb** [DexterInd/BrickPi3#69]
And yet another bug! Once in a while BP.reset_all() doesn't correctly reset everything. For example I'll be running two motors and do CTRL-C to terminate the program. As you can see in the code that it should run BP.reset_all(), which it does. However sometimes it will not stop the motors at all or even stop one motor but not the other. 

try:
    main()
except Exception as Inst:
    print(Inst)
except KeyboardInterrupt:
    pass
BP.reset_all()

**Comment by DexterInd** [comment]
Hi @graykevinb , thanks for your patience on this one.  I think this is actually an issue with your code; running CTRL+C will terminate the program.  You can do a few different things:

1.  On initiatlization, could you run `BP.reset_all()`
2.  Could you try `atexit`

Thanks @graykevinb !

**Comment by mattallen37** [comment]
@graykevinb can you share an example as simple as possible that demonstrates this behavior?

**Comment by graykevinb** [comment]
@DexterInd the code I put above is the error handling code in my program. Yes CTRL+C does terminate a program, but in my code there is error handling that runs BP.reset_all() on keyboard interrupt, CTRL+C. 
@mattallen37 I will attempt to create an example.

**Comment by graykevinb** [comment]
I've tried to create an example, but the error just happens too rarely to affectively test. I have tried many times and haven't got it to break.
I've included the code if you want to see it, but I couldn't get any errors. 

[error_crash.txt](https://github.com/DexterInd/BrickPi3/files/1045965/error_crash.txt)

**Comment by graykevinb** [comment]
Should I close this issue? I can't reproduce it sadly.
