### ISSUE TITLE
Issues with speed control in firmware v1.4.4

### ISSUE THREAD

**Issue by dlech** [DexterInd/BrickPi3#80]
I'm using ev3dev and just upgraded to firmware v1.4.4. The voltage compensation introduced in this firmware version seems to cause problems at 9V. I am running off of a variable voltage wall wart power supply. At 12V, motors seem to run normally. At 9V, however, the motor does not rotate.

Here are videos showing the difference. The only difference is the power supply voltage. The commands are the same.

12V: https://youtu.be/Vw6AnY2EMxg
9V: https://youtu.be/EfUtpgdzhdw

**Comment by mattallen37** [comment]
Solved with PR #81 (FW version 1.4.6).

**Comment by dlech** [comment]
Cool. It will be a week before I can try it out.

**Comment by dlech** [comment]
Cool. It will be a week before I can try it out.
