### ISSUE TITLE
Stacking two brickpi3's?

### ISSUE THREAD

**Issue by coffeedood** [DexterInd/BrickPi3#99]
Hello.  I just got two brickpi3's and I have stacked them on top of eachother and given them enough power.  How do I control the "stacked" brickpi3 with python script?  It seems like I need to go through a complex process of using each individual Brickpi3's ID.  I guess I have a second question which is how would I be able to do two Brickpi3's running ev3 dev?  I still have yet to figure out how to run a simple motor with a brickpi3 on ev3dev.  Any help would be greatly appreciated.  You can even send me an email response if you like at coffeedood@yahoo.com  
Thanks.

**Comment by RobertLucian** [comment]
> How do I control the "stacked" brickpi3 with python script? It seems like I need to go through a complex process of using each individual Brickpi3's ID.

Each BrickPi3 has a unique identifier that is permanently flashed (think of ROM memory). All you need to do is get the ID of every BrickPi3 you want to have stacked onto the Raspberry Pi and then run the `set_address` method for each one of them. That's all it is with it. I really encourage you to read the following thread carefully:
https://forum.dexterindustries.com/t/brickpi3-can-now-be-stacked/2748

> I guess I have a second question which is how would I be able to do two Brickpi3's running ev3 dev? I still have yet to figure out how to run a simple motor with a brickpi3 on ev3dev.

For this, I'm gonna bring @mattallen37 into this. He might have a better explanation for you.

**Comment by byWulf** [comment]
Also see the following examples in this repo to see what code you have to use:

* [Get the IDs for each BrickPi (important: only connect one to the raspberry pi at once for getting the ID)](https://github.com/DexterInd/BrickPi3/blob/master/Software/Python/Examples/Read_Info.py)
* [Use multiple BrickPi's at once, after you know their IDs](https://github.com/DexterInd/BrickPi3/blob/master/Software/Python/Examples/BrickPi3_Stack_Set_Address.py)

**Comment by dlech** [comment]
It would be better to ask ev3dev python questions at https://github.com/ev3dev/ev3dev-lang-python/issues
